version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: site-analysis-backend
    ports:
      - "8000:8000"
    # ADD THIS BLOCK ----------------
   # deploy:
    #  resources:
    #    limits:
    #      cpus: '1.0'   # Force it to use only 1 CPU core
    #      memory: 1024M # Force it to crash if it uses > 1GB RAM
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - site-analysis-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: site-analysis-frontend
    ports:
      - "8501:80"
    depends_on:
      - backend
    networks:
      - site-analysis-network

networks:
  site-analysis-network:
    driver: bridge
